config_version = 15

[audio]
enable_sounds = true

[backdrop]
blur_intensity = 0.59999998658895493
enabled = true

[bar.default]
background_opacity = 0.59999998658895493
center = [ "workspaces", "disc" ]
contact_shadow = true
end = [ "tray", "status", "recorder", "widget", "clipboard", "network", "output_volume", "battery" ]
font_weight = 400
hover_highlight = false
scale = 0.90000000596046448
shadow = true
start = [ "time", "sysmon", "spacer_2", "active_window" ]
thickness = 18

[battery]
warning_threshold = 20

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[control_center.calendar]
show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 64.0
    box_width = 1360.0
    cx = 683.0
    cy = 736.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        bands = 128
        centered = false
        reversed = false
        show_when_idle = false

[lockscreen]
blur_intensity = 0.0
edge_smoothness = 0.45000000000000001
tint_intensity = 0.0
transition = [ "disc" ]
transition_duration = 950.0
wallpaper = "/home/screenager/.local/share/noctalia/plugins/turntable/assets/night.png"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006"
]

    [lockscreen_widgets.grid]
    cell_size = 8
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 346.0
    cx = 335.0
    cy = 577.20001220703125
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 4.0
        center_password_text = false
        input_opacity = 0.34999999999999998
        input_radius = 4.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = false
        show_session_buttons = false
        show_unlock_hint = false
        show_weather = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 540.0
    box_width = 540.0
    cx = 984.0
    cy = 372.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        bloom_intensity = 0.69999999999999996
        fade_when_idle = true
        inner_diameter = 0.66000000000000003
        primary_color = "primary"
        ring_opacity = 0.65000000000000002
        rotation_speed = 0.25
        secondary_color = "tertiary"
        sensitivity = 1.3999999999999999
        visualization_mode = "rings"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 428.0
    box_width = 440.0
    cx = 1024.0
    cy = 406.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "screenager/turntable:record"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        accent = "primary"
        background = false
        show_info = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 336.0
    box_width = 377.0
    cx = 303.5
    cy = 305.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "screenager/turntable:clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        accent = "primary"
        background = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 133.0
    box_width = 372.0
    cx = 306.0
    cy = 543.70001220703125
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "screenager/turntable:login"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false
        greeting = "auto"
        name = "screenager"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 20.0
    box_width = 260.0
    cx = 170.0
    cy = 35.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "screenager/turntable:path"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        background = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 20.0
    box_width = 220.0
    cx = 1216.0
    cy = 35.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "screenager/turntable:battery"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        accent = "primary"
        background = false

[notification]
background_opacity = 0.59999998658895493

[osd]
background_opacity = 0.59999998658895493
position = "bottom_center"

[plugins]
enabled = [ "oldirtty/color_picker", "noctalia/screen_recorder", "screenager/turntable" ]

[shell]
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
screen_time_enabled = true

    [shell.launcher.providers.emoji]
    global = true

    [shell.panel]
    transparency_mode = "glass"

    [shell.screenshot]
    confirm_region = true
    directory = "~/Pictures/Screenshots"

[theme]
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "cava", "gtk3", "gtk4", "niri", "qt" ]
    community_ids = [ "claude-code", "codex", "zen-browser", "obsidian", "vscode", "zed", "fastfetch", "zathura" ]

[wallpaper]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/screenager/Pictures/Wallpapers/aesthetic-wallpapers-main/images/guy_sleeping_colored.png"

    [wallpaper.last]
    path = "/home/screenager/Pictures/Wallpapers/aesthetic-wallpapers-main/images/guy_sleeping_colored.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/screenager/Pictures/Wallpapers/aesthetic-wallpapers-main/images/guy_sleeping_colored.png"

[widget.disc]
size = 18
type = "screenager/turntable:disc"

[widget.media]
hide_album_art = true
hide_when_no_media = true

[widget.network]
show_label = false

[widget.output_volume]
show_label = false

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.spacer_2]
type = "spacer"

[widget.status]
type = "goodroot/noctwhspr:status"

[widget.tray]
drawer = true

[widget.widget]
type = "oldirtty/color_picker:widget"

[widget.workspaces]
pill_scale = 0.90000000000000002