-- Generated by Matugen. Signal handling lives in lua/polish.lua so this
-- module can be safely reloaded when the palette changes.
local M = {}

function M.setup()
  require("base16-colorscheme").setup {
     -- Background tones
     base00 = '#0f150e', -- Default Background
     base01 = '#1b211a', -- Lighter Background (status bars)
     base02 = '#252c24', -- Selection Background
     base03 = '#889484', -- Comments, Invisibles
     -- Foreground tones
     base04 = '#becab8', -- Dark Foreground (status bars)
     base05 = '#dee5d8', -- Default Foreground
     base06 = '#dee5d8', -- Light Foreground
     base07 = '#dee5d8', -- Lightest Foreground
     -- Accent colors
     base08 = '#ffb4ab', -- Variables, XML Tags, Errors
     base09 = '#9ccaff', -- Integers, Constants
     base0A = '#a5d29e', -- Classes, Search Background
     base0B = '#72dd71', -- Strings, Diff Inserted
     base0C = '#9ccaff', -- Regex, Escape Chars
     base0D = '#72dd71', -- Functions, Methods
     base0E = '#a5d29e', -- Keywords, Storage
     base0F = '#93000a', -- Deprecated, Embedded Tags
  }
end

return M
